doctrine:
    dbal:
        dbname: '%env(APP_DBNAME)%'
        host: '%env(APP_DBHOST)%'
        port: '%env(APP_DBPORT)%'
        user: '%env(APP_DBUSER)%'
        password: '%env(APP_DBPASSWORD)%'
        server_version: 8.0
        driver: pdo_mysql
        charset: UTF8
        logging: true
        profiling: true
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
