version: '3'

networks:
    nginx-php74-mysql8-node:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: sre-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - nginx-php74-mysql8-node

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: sre-php
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/project
        networks:
            - nginx-php74-mysql8-node

    mysql:
        image: mysql:8
        container_name: sre-mysql
        ports:
            - "4306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - nginx-php74-mysql8-node