version: '3'

networks:
    sre-app-network:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: sre-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
        restart: on-failure
        networks:
            - sre-app-network

    php: &default-app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: sre-php
        restart: always
        ports:
            - "9000:9000"
        environment:
            - "PHP_IDE_CONFIG=serverName=sre-app-docker"
            - "XDEBUG_CONFIG=client_host=host.docker.internal"
        volumes:
            - ./:/var/www/app
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        depends_on:
            - db
            - redis
        networks:
            - sre-app-network
        user: 1000:1000

    queue:
        <<: *default-app
        build:
            context: .
            dockerfile: ./docker/queue/Dockerfile
        container_name: sre-queue
        volumes:
            - ./:/var/www/app
            - ./docker/mysql:/var/lib/mysql
            - ./docker/scripts:/var/www/scripts
        ports:
            - "9001:9000"
        depends_on:
            - php

    db:
        image: mysql:8
        container_name: sre-db
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "${APP_DBPORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${APP_DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${APP_DBNAME}
            MYSQL_USER: ${APP_DBUSER}
            MYSQL_PASSWORD: ${APP_DBPASSWORD}
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - sre-app-network

    redis:
        image: redis:alpine
        container_name: sre-redis
        ports:
            - "6379:6379"
        networks:
            - sre-app-network